// <auto-generated />
using System;
using HotelRoomBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelRoomBooking.Migrations
{
    [DbContext(typeof(HotelRoomDbContext))]
    [Migration("20251110181551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelRoomBooking.Domain.BookedNight", b =>
                {
                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.HasKey("RoomId", "Date");

                    b.HasIndex("BookingId");

                    b.ToTable("BookedNights");
                });

            modelBuilder.Entity("HotelRoomBooking.Domain.Booking", b =>
                {
                    b.Property<long>("BookingReference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("BookingReference"));

                    b.Property<long>("BookedRoomId")
                        .HasColumnType("bigint");

                    b.Property<string>("GuestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("integer");

                    b.HasKey("BookingReference");

                    b.HasIndex("BookedRoomId");

                    b.HasIndex("HotelName");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HotelRoomBooking.Domain.Hotel", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Name");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("HotelRoomBooking.Domain.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HotelName");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("HotelRoomBooking.Domain.BookedNight", b =>
                {
                    b.HasOne("HotelRoomBooking.Domain.Booking", null)
                        .WithMany("BookedNights")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelRoomBooking.Domain.Room", null)
                        .WithMany("BookedNights")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelRoomBooking.Domain.Booking", b =>
                {
                    b.HasOne("HotelRoomBooking.Domain.Room", "BookedRoom")
                        .WithMany()
                        .HasForeignKey("BookedRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelRoomBooking.Domain.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookedRoom");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelRoomBooking.Domain.Room", b =>
                {
                    b.HasOne("HotelRoomBooking.Domain.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelRoomBooking.Domain.Booking", b =>
                {
                    b.Navigation("BookedNights");
                });

            modelBuilder.Entity("HotelRoomBooking.Domain.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelRoomBooking.Domain.Room", b =>
                {
                    b.Navigation("BookedNights");
                });
#pragma warning restore 612, 618
        }
    }
}
